"use client";

import { useState, useEffect } from "react";
import CenterModal from "@/components/common/Modals/CenterModal";
import Button from "@/components/common/Button";
import {
    CategoryField,
    DurationField,
    InstantDateField,
    LevelField,
    SESSION_FIELD_LABELS,
    SessionDetailsField,
    SkillField,
    type PickedSkill,
    type SessionCategory,
} from "@/components/schedule/forms/SessionFormFields";
import { LocalizationProvider, MobileTimePicker } from "@mui/x-date-pickers";
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";
// Commits the displayed time on OK - see CommitActionBar for the MUI onAccept quirk.
import CommitActionBar from "@/components/common/Input/Picker/CommitActionBar";
import dayjs from "dayjs";
import utc from "dayjs/plugin/utc";
import timezone from "dayjs/plugin/timezone";
import { POST_API, GET_API } from "@/api/request";
import { endpoints } from "@/api/constants";
import { showToast } from "@/components/common/Toast";
import { getApiErrorMessage } from "@/utils/apiError";
import { useQuery } from "@tanstack/react-query";
import { useAppStore } from "@/store/useAppStore";
import useInnerWidth from "@/hooks/useInnerWidth";
import ModalCloseIcon from "@/assets/icons/ModalCloseIcon";
import { extractTimezoneOffset } from "@/utils/timeFunctions";

dayjs.extend(utc);
dayjs.extend(timezone);

/* Full-screen mobile modal: align wrap to top and make content fill viewport */
const fullScreenMobileStyles = (
    <style
        dangerouslySetInnerHTML={{
            __html: `
            @media (max-width: 767px) {
                .ant-modal-wrap:has(.new-event-modal-fullscreen-mobile) {
                    align-items: flex-start !important;
                }
                .new-event-modal-fullscreen-mobile.ant-modal {
                    max-width: 100vw !important;
                    top: 0 !important;
                    padding: 0 !important;
                }
                .new-event-modal-fullscreen-mobile .ant-modal-content {
                    height: 100dvh !important;
                    max-height: 100dvh !important;
                    border-radius: 0 !important;
                }
            }
        `,
        }}
    />
);

interface NewEventModalProps {
    isOpen: boolean;
    onClose: () => void;
    onSubmit?: (data: NewEventData) => void;
    /** When provided, used for the instant session. When omitted, slots for the selected date are fetched and the first slot is used. */
    volunteer_slot_id?: string;
}

export interface NewEventData {
    select_date: Date | null;
    duration: string;
    start_time: string;
    description: string;
    tags: string[];
}

/** Request body for POST /api/v1/session/instant_session */
interface InstantSessionPayload {
    volunteer_slot_id: string;
    date: string;
    duration: number;
    start_time: string;
    description: string;
    // Title is generated by the API from category + skill ("Academic Session - Math").
    session_category: SessionCategory;
    tag_ids: string[];
    grade_level: string | null;
    expertise_level: string | null;
}

const timezoneMapping: Record<string, string> = {
    AKST: "America/Anchorage",
    AKDT: "America/Anchorage",
    AST: "America/Halifax",
    ADT: "America/Halifax",
    CST: "America/Chicago",
    CDT: "America/Chicago",
    EST: "America/New_York",
    EDT: "America/New_York",
    HST: "Pacific/Honolulu",
    HDT: "Pacific/Honolulu",
    MST: "America/Denver",
    MDT: "America/Denver",
    MT: "America/Denver",
    NST: "America/St_Johns",
    NDT: "America/St_Johns",
    PST: "America/Los_Angeles",
    PDT: "America/Los_Angeles",
    PT: "America/Los_Angeles",
    CT: "America/Chicago",
    ET: "America/New_York",
    IST: "Asia/Kolkata",
};

export default function NewEventModal({
    isOpen,
    onClose,
    onSubmit,
    volunteer_slot_id: volunteerSlotIdProp,
}: NewEventModalProps) {
    const [formData, setFormData] = useState<NewEventData>({
        select_date: new Date(),
        duration: "30",
        start_time: "",
        description: "",
        tags: [],
    });

    // Same hierarchy as the learner's request form: one category, exactly one skill (a
    // volunteer can't teach two things in one session) and the level taught.
    const [category, setCategory] = useState<SessionCategory | "">("");
    const [skill, setSkill] = useState<PickedSkill | null>(null);
    const [level, setLevel] = useState("");
    const [fieldErrors, setFieldErrors] = useState<{ category?: string; skill?: string; level?: string }>({});
    const resetSkillFields = () => {
        setCategory("");
        setSkill(null);
        setLevel("");
        setFieldErrors({});
    };

    const [isSubmitting, setIsSubmitting] = useState(false);
    // Temporary time state for mobile time picker dialog
    const [tempTime, setTempTime] = useState<dayjs.Dayjs | null>(null);
    // Fully controlled open state, so the custom action bar (below) can close the
    // picker itself instead of relying on MUI's internal accept/dismiss diffing.
    const [isTimePickerOpen, setIsTimePickerOpen] = useState(false);
    // Track selected meridiem explicitly to ensure PM hours show immediately
    const [selectedMeridiem, setSelectedMeridiem] = useState<string | null>(null);

    const { volunteerDetails, volunteerUtcOffset } = useAppStore();
    const timezoneRaw =
        (
            volunteerDetails as {
                volunteer_contact_details?: { timezone?: string; utc_offset?: string };
            }
        )?.volunteer_contact_details?.timezone ?? "";

    const rawAbbreviation = timezoneRaw.includes(" - ")
        ? (timezoneRaw.split(" - ")[0]?.trim() ?? "")
        : "";

    const ianaTimezone = timezoneMapping[rawAbbreviation] || null;

    // Use IANA timezone name if available, otherwise raw abbreviation
    const volunteerTimezone = ianaTimezone || rawAbbreviation;

    // Get the current active abbreviation (handles NST -> NDT transition)
    const activeAbbreviation = ianaTimezone
        ? dayjs().tz(ianaTimezone).format("z")
        : rawAbbreviation;

    // Get UTC offset from volunteerDetails or store, with fallback to extracting from timezone string
    const volunteerUtcOffsetValue =
        (volunteerDetails as { volunteer_contact_details?: { utc_offset?: string } })
            ?.volunteer_contact_details?.utc_offset ||
        volunteerUtcOffset ||
        (timezoneRaw ? extractTimezoneOffset(timezoneRaw) : null);

    // Get current time in volunteer's timezone
    const getNowInVolunteerTimezone = () => {
        // dayjs.tz handles DST correctly when given an IANA name
        return dayjs.tz(undefined, volunteerTimezone || "UTC");
    };

    // Get today's date in YYYY-MM-DD format in volunteer's timezone
    const getTodayDate = () => {
        return getNowInVolunteerTimezone().format("YYYY-MM-DD");
    };

    // Get tomorrow's date in YYYY-MM-DD format in volunteer's timezone
    const getTomorrowDate = () => {
        return getNowInVolunteerTimezone().add(1, "day").format("YYYY-MM-DD");
    };

    // Get today's date as a Date object in volunteer's timezone
    const getTodayDateObject = (): Date => {
        const now = getNowInVolunteerTimezone();
        // Create a Date object representing the date in "local" time for the datepicker
        return new Date(now.year(), now.month(), now.date());
    };

    // Reset all form fields when modal opens
    useEffect(() => {
        if (isOpen) {
            // Get today's date in volunteer's timezone
            const todayInTimezone = getTodayDateObject();
            setFormData({
                select_date: todayInTimezone,
                duration: "30",
                start_time: "",
                description: "",
                tags: [],
            });
            setDescriptionError(null);
            resetSkillFields();
            setTempTime(null);
            setIsTimePickerOpen(false);
            setSelectedMeridiem(null);
        }
    }, [isOpen, volunteerUtcOffsetValue, volunteerTimezone]);

    // Sync tempTime with formData.start_time
    useEffect(() => {
        if (formData.start_time) {
            setTempTime(dayjs.tz(formData.start_time, "HH:mm", volunteerTimezone || "UTC"));
        } else {
            setTempTime(null);
        }
    }, [formData.start_time, volunteerTimezone]);

    const handleDateChange = (date: Date | null) => {
        setFormData((prev) => ({ ...prev, select_date: date }));
    };

    const handleDurationChange = (value: string | number) => {
        setFormData((prev) => ({ ...prev, duration: String(value) }));
    };

    // Fetch available slots for the selected date
    const { data: slotsData, refetch: refetchSlots } = useQuery({
        queryKey: ["available-slots", dayjs(formData.select_date).format("YYYY-MM-DD")],
        queryFn: async () => {
            if (!formData.select_date) return [];
            const dateStr = dayjs(formData.select_date).format("YYYY-MM-DD");
            try {
                const res = await GET_API(
                    endpoints.volunteer_slot.getAvailableDaysForDate(dateStr)
                );
                return res?.data?.slots || [];
            } catch (error) {
                console.error("Error fetching slots:", error);
                return [];
            }
        },
        enabled: !!formData.select_date,
    });

    // The volunteer's own still-open instant sessions - so we can pre-warn on an overlap
    // instead of only finding out from the server's generic error after submit.
    const { data: myOpenSessionsData } = useQuery({
        queryKey: ["my-open-instant-sessions-overlap"],
        queryFn: async () => {
            try {
                const res = await GET_API(
                    endpoints.session.getMyInstantSessions(1, 100, undefined, "open")
                );
                return (res?.data?.items ?? []) as any[];
            } catch {
                return [];
            }
        },
        enabled: isOpen,
    });

    const handleTimeChange = (time: dayjs.Dayjs | null) => {
        if (time) {
            setFormData((prev) => ({ ...prev, start_time: time.format("HH:mm") }));
        }
    };

    const handleTimeAccept = (time: dayjs.Dayjs | null) => {
        if (time) {
            setFormData((prev) => ({ ...prev, start_time: time.format("HH:mm") }));
        }
    };

    const shouldDisableTime = (timeValue: dayjs.Dayjs, clockType: string | any) => {
        if (!formData.select_date) return false;

        const nowInTz = getNowInVolunteerTimezone();
        const selectedDateStr = dayjs(formData.select_date).format("YYYY-MM-DD");
        const currentDateStr = nowInTz.format("YYYY-MM-DD");

        // If selected date is in the past, disable all times
        if (selectedDateStr < currentDateStr) {
            return true;
        }

        // Helper function to check if a time slot is booked
        const isTimeSlotBooked = (timeStr: string): boolean => {
            if (!slotsData || !Array.isArray(slotsData)) return false;
            return slotsData.some((slot: any) => {
                return timeStr >= slot.start_time && timeStr < slot.end_time;
            });
        };

        const isToday = selectedDateStr === currentDateStr;

        if (clockType === "hours") {
            const hour24 = timeValue.hour();

            if (isToday && hour24 < nowInTz.hour()) {
                return true;
            }

            // Check if all minute slots in this hour are unavailable (past or booked)
            const minutesToCheck = Array.from({ length: 60 }, (_, minute) => minute);
            return minutesToCheck.every((minute) => {
                const checkTime = timeValue.minute(minute).second(0);
                if (isToday && checkTime.isBefore(nowInTz, "minute")) return true;
                return isTimeSlotBooked(checkTime.format("HH:mm"));
            });
        } else if (clockType === "minutes") {
            const timeStr = timeValue.format("HH:mm");
            if (isToday && timeValue.isBefore(nowInTz, "minute")) return true;
            return isTimeSlotBooked(timeStr);
        } else if (clockType === "meridiem") {
            if (isToday && nowInTz.format("A") === "PM" && timeValue.format("A") === "AM") {
                return true;
            }
        }

        return false;
    };

    const [descriptionError, setDescriptionError] = useState<string | null>(null);
    const handleDescriptionChange = (value: string) => {
        if (value.trim()) setDescriptionError(null);
        setFormData((prev) => ({ ...prev, description: value }));
    };

    // Helper function to check if time slots overlap
    const areSlotsOverlapping = (
        start1: string,
        end1: string,
        start2: string,
        end2: string
    ): boolean => {
        const start1Minutes = dayjs(start1, "HH:mm");
        const end1Minutes = dayjs(end1, "HH:mm");
        const start2Minutes = dayjs(start2, "HH:mm");
        const end2Minutes = dayjs(end2, "HH:mm");

        return start1Minutes.isBefore(end2Minutes) && end1Minutes.isAfter(start2Minutes);
    };

    // Helper function to calculate end time from start time and duration
    const calculateEndTime = (startTime: string, durationMinutes: number): string => {
        return dayjs(startTime, "HH:mm").add(durationMinutes, "minute").format("HH:mm");
    };

    const handleSubmit = async () => {
        const missing = {
            category: category ? undefined : "Please choose a category.",
            skill: skill ? undefined : "Please choose a skill.",
            level: level ? undefined : "Please choose a level.",
        };
        if (missing.category || missing.skill || missing.level || !formData.description?.trim()) {
            setFieldErrors(missing);
            if (!formData.description?.trim()) setDescriptionError("Please describe the session details and expectations.");
            showToast({ message: "Please complete the highlighted fields", type: "error" });
            return;
        }
        if (!formData.duration || !formData.start_time) {
            showToast({ message: "Please choose a date, start time and duration", type: "error" });
            return;
        }
        // Validate that the selected time is not in the past
        const dateStr = formData.select_date
            ? dayjs(formData.select_date).format("YYYY-MM-DD")
            : dayjs().format("YYYY-MM-DD");

        // Get current time in volunteer's timezone
        const nowInTz = getNowInVolunteerTimezone();
        const currentDateStr = nowInTz.format("YYYY-MM-DD");
        const currentTimeStr = nowInTz.format("HH:mm");

        // Check if selected date is in the past
        if (dateStr < currentDateStr) {
            showToast({ message: "Cannot create session for a past date", type: "error" });
            return;
        }

        // Check if selected time is in the past (only for today)
        if (dateStr === currentDateStr) {
            const selectedTimeStr = formData.start_time;
            if (selectedTimeStr < currentTimeStr) {
                showToast({ message: "Cannot create session for a past time", type: "error" });
                return;
            }
        }

        // Check for overlapping time slots
        if (slotsData && Array.isArray(slotsData) && slotsData.length > 0) {
            const durationMinutes = Number(formData.duration) || 0;
            const newStartTime = formData.start_time;
            const newEndTime = calculateEndTime(newStartTime, durationMinutes);

            // Check if the new slot overlaps with any existing slot
            const hasOverlap = slotsData.some((slot: any) => {
                if (!slot.start_time || !slot.end_time) return false;

                // Check for overlap
                return areSlotsOverlapping(
                    newStartTime,
                    newEndTime,
                    slot.start_time,
                    slot.end_time
                );
            });

            if (hasOverlap) {
                showToast({
                    message: "Time slot overlaps with an existing session",
                    type: "error",
                });
                return;
            }
        }

        // Pre-warn against the volunteer's own already-open instant sessions (the server
        // rejects this too, but only with a generic message after submit).
        {
            const myOpen = Array.isArray(myOpenSessionsData) ? myOpenSessionsData : [];
            if (myOpen.length > 0) {
                const durationMinutes = Number(formData.duration) || 0;
                const s = formData.start_time;
                const e = calculateEndTime(s, durationMinutes);
                const overlapsOpen = myOpen.some(
                    (os) =>
                        os?.volunteer_start_date === dateStr &&
                        os?.volunteer_start_time &&
                        os?.volunteer_end_time &&
                        areSlotsOverlapping(s, e, os.volunteer_start_time, os.volunteer_end_time)
                );
                if (overlapsOpen) {
                    showToast({
                        message: "You've already opened an instant session that overlaps this time",
                        type: "error",
                    });
                    return;
                }
            }
        }
        let volunteer_slot_id = volunteerSlotIdProp;
        if (!volunteer_slot_id) {
            // Generate a unique 64-character hex ID (SHA-256 format)
            const array = new Uint8Array(32);
            window.crypto.getRandomValues(array);
            volunteer_slot_id = Array.from(array)
                .map((b) => b.toString(16).padStart(2, "0"))
                .join("");
        }
        const payload: InstantSessionPayload = {
            volunteer_slot_id,
            date: dateStr,
            duration: Number(formData.duration) || 0,
            start_time: formData.start_time,
            description: formData.description.trim(),
            session_category: category as SessionCategory,
            tag_ids: [skill!.skill_id],
            grade_level: category === "academic" ? level : null,
            expertise_level: category === "non_academic" ? level : null,
        };
        setIsSubmitting(true);
        try {
            const res = await POST_API(endpoints.session.createInstantSession, payload);
            if (res?.status === 200 || res?.status === 201) {
                showToast({ message: "Instant session posted", type: "success" });
                onSubmit?.({ ...formData, tags: skill ? [skill.skill_name] : [] });
                setFormData({
                    select_date: getTodayDateObject(),
                    duration: "30",
                    start_time: "",
                    description: "",
                    tags: [],
                });
                resetSkillFields();
                setTempTime(null);
                setIsTimePickerOpen(false);
                onClose();
            } else {
                showToast({ message: "Failed to create instant session", type: "error" });
            }
        } catch (err) {
            showToast({ message: getApiErrorMessage(err, "Failed to post instant session"), type: "error" });
        } finally {
            setIsSubmitting(false);
        }
    };

    const handleCancel = () => {
        setFormData({
            select_date: getTodayDateObject(),
            duration: "30",
            start_time: "",
            description: "",
            tags: [],
        });
        setDescriptionError(null);
        resetSkillFields();
        setTempTime(null);
        setIsTimePickerOpen(false);
        setSelectedMeridiem(null);
        onClose();
    };

    const innerWidth = useInnerWidth();
    const isMobile = innerWidth > 0 && innerWidth < 768;
    const mobileHeader = (
        <div className="flex items-center gap-3 w-full">
            <button
                type="button"
                onClick={handleCancel}
                className="flex items-center justify-center rounded-full p-0 border-0 bg-transparent active:scale-90 transition-all duration-200 cursor-pointer"
                aria-label="Close"
            >
                <ModalCloseIcon className="active:scale-90 transition-all duration-200" />
            </button>
            <p className="text-[20px] font-medium text-[#1a1a1a]">Post an Instant Session</p>
        </div>
    );

    return (
        <>
            {fullScreenMobileStyles}
            <CenterModal
                title="Post an Instant Session"
                topContent={
                    <p className="text-sm text-gray-500 font-normal !mt-0">
                        Post what you can teach - a learner can claim it.
                    </p>
                }
                headerComponent={isMobile ? mobileHeader : undefined}
                hideCloseIcon={isMobile}
                isOpen={isOpen}
                onClose={handleCancel}
                width={620}
                hideFooter={true}
                customClassName="new-event-modal-fullscreen-mobile !rounded-3xl max-md:!w-screen max-md:!min-h-[100dvh] max-md:!h-[100dvh] max-md:!max-h-[100dvh] max-md:!top-0 max-md:!rounded-none max-md:!m-0"
                rootClassName="!rounded-3xl overflow-hidden max-md:!min-h-full max-md:!h-full"
                headerClassName="!px-6 !py-5"
                bodyClassName="md:!px-6 !p-[20px]"
            >
                <div className="flex flex-col gap-5 max-md:gap-5">
                    <CategoryField
                        value={category}
                        error={fieldErrors.category}
                        onChange={(value) => {
                            setCategory(value);
                            setSkill(null);
                            setLevel("");
                            setFieldErrors({});
                        }}
                    />
                    <SkillField
                        category={category}
                        value={skill}
                        error={fieldErrors.skill}
                        onChange={(value) => {
                            setSkill(value);
                            setFieldErrors((e) => ({ ...e, skill: undefined }));
                        }}
                    />
                    <LevelField
                        category={category}
                        value={level}
                        error={fieldErrors.level}
                        onChange={(value) => {
                            setLevel(value);
                            setFieldErrors((e) => ({ ...e, level: undefined }));
                        }}
                    />
                    <SessionDetailsField
                        value={formData.description}
                        error={descriptionError}
                        placeholder="What will you cover? Anything the learner should know or bring?"
                        onChange={handleDescriptionChange}
                    />

                    <InstantDateField
                        value={dayjs(formData.select_date).format("YYYY-MM-DD")}
                        today={getTodayDate()}
                        tomorrow={getTomorrowDate()}
                        onChange={(value) => {
                            const [y, m, d] = value.split("-").map(Number);
                            handleDateChange(new Date(y, m - 1, d));
                        }}
                    />

                    {/* Start Time */}
                    <div className="flex flex-col gap-2">
                        <label className="text-base font-medium text-[#121212]">
                            {SESSION_FIELD_LABELS.startTime}{activeAbbreviation ? ` (${activeAbbreviation})` : ""} <span aria-hidden="true">*</span>
                        </label>
                        <div className="w-full">
                            <LocalizationProvider dateAdapter={AdapterDayjs}>
                                <MobileTimePicker
                                    format="h:mm A"
                                    minutesStep={5}
                                    timezone={volunteerTimezone || "UTC"}
                                    value={tempTime}
                                    open={isTimePickerOpen}
                                    onChange={(time) => {
                                        // Always update tempTime when time changes
                                        // This includes when user clicks AM/PM (meridiem changes)
                                        // This ensures mobile picker shows hours correctly when PM is selected
                                        setTempTime(time);
                                        // Track meridiem explicitly when it changes
                                        if (time) {
                                            const meridiem = time.format("A");
                                            setSelectedMeridiem(meridiem);
                                        }
                                    }}
                                    onOpen={() => {
                                        setIsTimePickerOpen(true);

                                        // Fetch slots when time picker opens
                                        // This ensures we have the latest slot data for overlap checking
                                        if (formData.select_date) {
                                            refetchSlots();
                                        }

                                        // If tempTime is null, set default time based on current time in volunteer's timezone
                                        // This ensures hours are visible immediately when picker opens
                                        if (!tempTime) {
                                            // Same default as the learner's request form: the next
                                            // 5 minutes today, 9:00 AM tomorrow.
                                            const nowInTz = getNowInVolunteerTimezone();
                                            const isToday =
                                                dayjs(formData.select_date).format("YYYY-MM-DD") === nowInTz.format("YYYY-MM-DD");
                                            const defaultTime = isToday
                                                ? nowInTz
                                                      .minute(0)
                                                      .second(0)
                                                      .millisecond(0)
                                                      .add(Math.ceil((nowInTz.minute() + 1) / 5) * 5, "minute")
                                                : nowInTz.hour(9).minute(0).second(0).millisecond(0);

                                            setTempTime(defaultTime);
                                            setSelectedMeridiem(defaultTime.format("A"));
                                        } else {
                                            // If tempTime exists, track its meridiem
                                            const meridiem = tempTime.format("A");
                                            setSelectedMeridiem(meridiem);
                                        }
                                    }}
                                    onClose={() => {
                                        // A genuine cancel/dismiss (backdrop click, Escape) - discard
                                        // the in-progress draft and fall back to the committed value.
                                        setIsTimePickerOpen(false);
                                        setTempTime(
                                            formData.start_time
                                                ? dayjs.tz(formData.start_time, "HH:mm", volunteerTimezone || "UTC")
                                                : null
                                        );
                                    }}
                                    shouldDisableTime={shouldDisableTime}
                                    closeOnSelect={false}
                                    slots={{ actionBar: CommitActionBar }}
                                    slotProps={{
                                        actionBar: {
                                            onCancelClick: () => setIsTimePickerOpen(false),
                                            onAcceptClick: () => {
                                                if (tempTime) {
                                                    handleTimeAccept(tempTime);
                                                }
                                                setIsTimePickerOpen(false);
                                            },
                                        } as any,
                                        textField: {
                                            placeholder: "Select time",
                                            sx: {
                                                width: "100%",
                                                "& .MuiOutlinedInput-root": {
                                                    borderRadius: "12px",
                                                    fontSize: "16px",
                                                    height: "48px",
                                                    backgroundColor: "#ffffff",
                                                    "& fieldset": {
                                                        border: "1px solid #e5e7eb",
                                                    },
                                                    "&:hover": {
                                                        backgroundColor: "#ffffff",
                                                        "& fieldset": {
                                                            border: "1px solid #9ca3af",
                                                        },
                                                    },
                                                    "&.Mui-focused": {
                                                        backgroundColor: "#ffffff",
                                                        "& fieldset": {
                                                            border: "1px solid #000000",
                                                        },
                                                    },
                                                },
                                                "& .MuiInputBase-input": {
                                                    padding: "4px 14px",
                                                    fontSize: "16px",
                                                    color: "#121212",
                                                    height: "48px",
                                                    display: "flex",
                                                    alignItems: "center",
                                                },
                                                "& .MuiInputBase-input::placeholder": {
                                                    color: "#808080",
                                                    opacity: 1,
                                                    fontSize: "16px",
                                                    fontWeight: 400,
                                                },
                                            },
                                        },
                                    }}
                                />
                            </LocalizationProvider>
                        </div>
                    </div>

                    <DurationField
                        value={Number(formData.duration) || null}
                        onChange={(value) => handleDurationChange(value)}
                    />

                    {/* Action Buttons */}
                    <div className="hidden md:flex gap-3 pt-5 pb-2 border-t border-stroke">
                        <Button
                            title="Cancel"
                            onClick={handleCancel}
                            customClassName="flex-1 !bg-white !text-black !font-medium !rounded-2xl !border !border-gray-200 hover:!bg-gray-50 !py-3"
                        />
                        <Button
                            title={isSubmitting ? "Posting..." : "Post Session"}
                            onClick={handleSubmit}
                            disabled={isSubmitting}
                            customClassName="flex-1 !bg-black !text-white !font-medium !rounded-2xl !py-3"
                        />
                    </div>
                </div>
                <div className="flex md:hidden gap-3 pt-5 border-t border-stroke">
                    <Button
                        title="Cancel"
                        onClick={handleCancel}
                        customClassName="flex-1 !bg-white !text-black !font-medium !rounded-2xl !border !border-gray-200 !py-3"
                    />
                    <Button
                        title={isSubmitting ? "Posting..." : "Post Session"}
                        onClick={handleSubmit}
                        disabled={isSubmitting}
                        customClassName="flex-1 !bg-black !text-white !font-medium !rounded-2xl !py-3"
                    />
                </div>
            </CenterModal>
        </>
    );
}
