import nationalities from "@/data/nationalities.json";
import timezones from "@/data/selectiveTimeZones.json";

export const LearnerOnboardingConstants = {
    title: "Enroll a learner",
    description:
        "Thank you for your interest in joining MelodyWings. Fill out the form below and we'll get you a good fit.",
};

// Parent/Guardian Information Fields
const ParentGuardianFields: FormField[] = [
    {
        id: "parent_first_name",
        label: "First Name",
        inputType: "text",
        placeholder: "Enter First Name",
        gridCols: 1,
    },
    {
        id: "parent_last_name",
        label: "Last Name",
        inputType: "text",
        placeholder: "Enter Last Name",
        gridCols: 1,
    },
    {
        id: "relationship_to_learner",
        label: "Relationship to the Learner",
        inputType: "select-creatable",
        creatable: true,
        variant: "single",
        showSearch: true,
        placeholder: "Select relationship",
        gridCols: 1,
        options: [
            { label: "Aunt/Uncle", value: "aunt_uncle" },
            { label: "Caregiver/Nanny", value: "caregiver_nanny" },
            { label: "Coach", value: "coach" },
            { label: "Colleague", value: "colleague" },
            { label: "Counselor/Therapist", value: "counselor_therapist" },
            { label: "Cousin", value: "cousin" },
            { label: "Employer/Supervisor", value: "employer_supervisor" },
            { label: "Friend", value: "friend" },
            { label: "Grandparent", value: "grandparent" },
            { label: "Guardian", value: "guardian" },
            { label: "Mentor", value: "mentor" },
            { label: "Neighbor", value: "neighbor" },
            { label: "Parent", value: "parent" },
            { label: "Sibling", value: "sibling" },
            { label: "Social Worker", value: "social_worker" },
            { label: "Spouse/Partner", value: "spouse_partner" },
            { label: "Teacher/Educator", value: "teacher_educator" },
        ],
    },
    {
        id: "",
        inputType: "parent",
    },
    {
        id: "parent_email",
        label: "Email address",
        inputType: "text",
        placeholder: "abc@example.com",
        gridCols: 1,
    },
    {
        id: "parent_contact_number",
        label: "Guardian contact number",
        sublabel: "(with country code)",
        inputType: "contact-input",
        placeholder: "Enter contact number",
        sublabelAlignment: "right",
        gridCols: 1,
        disabled: false,
    },
    // {
    //     id: "parent_address",
    //     label: "Address",
    //     inputType: "textarea",
    //     placeholder: "Type address here",
    //     gridCols: 2,
    //     inputClassName: "w-[49%]",
    // }
];

// Learner's Personal Information Fields
const LearnerPersonalFields: FormField[] = [
    {
        id: "learner_first_name",
        label: "First Name",
        inputType: "text",
        placeholder: "Enter First Name",
        gridCols: 1,
        required: true,
    },
    {
        id: "learner_last_name",
        label: "Last Name",
        inputType: "text",
        placeholder: "Enter Last Name",
        gridCols: 1,
        required: true,
    },
    {
        id: "learner_date_of_birth",
        label: "Date of Birth",
        inputType: "birthdatepicker",
        placeholder: "DD/MM/YYYY",
        format: "DD-MM-YYYY",
        gridCols: 1,
        required: true,
        birthDatePicker: { minAge: 0, maxAge: 100 },
    },
    {
        id: "learner_gender",
        label: "Gender",
        inputType: "radio",
        options: [
            { label: "Male", value: "male" },
            { label: "Female", value: "female" },
            { label: "Prefer not to reveal", value: "not_specified" },
        ],
        gridCols: 1,
        required: true,
    },
    {
        id: "learner_preferred_pronoun",
        label: "Preferred Pronoun",
        inputType: "select",
        placeholder: "Select Pronoun",
        options: [
            { label: "He/Him", value: "he_him" },
            { label: "She/Her", value: "she_her" },
            { label: "They/Them", value: "they_them" },
        ],
        gridCols: 1,
        required: true,
    },
    {
        id: "learner_primary_language",
        label: "Primary Language",
        inputType: "async-select",
        creatable: true,
        showSearch: true,
        endpoint: "languages",
        variant: "single",
        responseAsLabel: "language_name",
        responseAsValue: "language_name",
        placeholder: "Don't see your option? Type it in to add.",
        gridCols: 1,
        required: true,
    },
    {
        parent: "learner_contact_details",
        id: "email",
        label: "Email Address",
        inputType: "text",
        placeholder: "Enter email",
        gridCols: 1,
        required: true,
    },
    {
        parent: "learner_contact_details",
        id: "contact_number",
        label: "Contact Number",
        inputType: "contact-input",
        sublabelAlignment: "right",
        gridCols: 1,
        disabled: false,
        required: true,
    },
    {
        parent: "learner_contact_details",
        id: "zip_code",
        label: "Zip Code",
        inputType: "text",
        placeholder: "Enter Zip Code",
        gridCols: 1,
        required: true,
    },
    {
        parent: "learner_contact_details",
        id: "country",
        label: "Country of Residence",
        inputType: "select",
        placeholder: "Select Country of Residence",
        options: nationalities,
        showSearch: true,
        gridCols: 1,
        required: true,
    },
    {
        parent: "learner_contact_details",
        id: "timezone",
        label: "Time Zone",
        inputType: "select",
        placeholder: "Search or select time zone",
        showSearch: true,
        options: timezones,
        gridCols: 1,
        inputClassName: "!w-full",
        required: true,
    },
];

// Disability-Specific Information Fields
const DisabilityInfoFields: FormField[] = [
    {
        id: "type_of_developmental_disability",
        label: "Type of Developmental Disability",
        sublabel: "(e.g., autism, down syndrome, ADHD, etc.)",
        inputType: "async-select",
        creatable: true,
        endpoint: "development_disabilities",
        variant: "single",
        responseAsLabel: "development_disability_name",
        responseAsValue: "development_disability_name",
        placeholder: "Don't see your option? Type it in to add.",
        gridCols: 1,
        required: true,
    },
    {
        id: "level_of_support_needed",
        label: "Level of Support Needed",
        inputType: "radio",
        options: [
            { label: "Mild", value: "mild" },
            { label: "Moderate", value: "moderate" },
            { label: "Extensive", value: "extensive" },
        ],
        gridCols: 1,
        sublabel: " ",
        className: "w-full h-full mt-2 md:mt-4",
        required: true,
    },
    {
        id: "assistive_device_used",
        label: "Assistive Devices Used",
        sublabel: "(E.g. , Hearing aids, Wheelchair)",
        inputType: "async-select",
        endpoint: "assistive_devices",
        variant: "single",
        creatable: true,
        responseAsLabel: "assistive_device_name",
        responseAsValue: "assistive_device_name",
        placeholder: "Don't see your option? Type it in to add.",
        gridCols: 1,
        required: true,
    },
    {
        id: "communication_style",
        label: "Communication Style",
        sublabel: "(e.g., verbal, sign language, AAC device)",
        inputType: "async-select",
        endpoint: "communication_styles",
        variant: "single",
        creatable: true,
        responseAsLabel: "communication_style_name",
        responseAsValue: "communication_style_name",
        placeholder: "Don't see your option? Type it in to add.",
        gridCols: 1,
        required: true,
    },
    {
        id: "behavioral_concerns",
        label: "Behavioral Concerns",
        sublabel: "(e.g., triggers, behaviors, suggested responses)",
        inputType: "text",
        placeholder: "Enter here",
        gridCols: 1,
    },
    {
        id: "behavior_support_strategies",
        label: "Behavior Support Strategies",
        sublabel: "(e.g., positive reinforcement, breaks)",
        inputType: "select-creatable",
        variant: "multi",
        placeholder: "Don't see your option? Type it in to add.",
        gridCols: 1,
        options: [
            { label: "Clear Instructions", value: "clear_instructions" },
            { label: "Deep Breathing", value: "deep_breathing" },
            { label: "Express Through Art", value: "express_through_art" },
            { label: "Give Comfort Item", value: "give_comfort_item" },
            { label: "Keep Consistent Routine", value: "keep_consistent_routine" },
            { label: "Offer Fidget Toys", value: "offer_fidget_toys" },
            { label: "Physical Activity", value: "physical_activity" },
            { label: "Play Calming Music", value: "play_calming_music" },
            { label: "Practice Grounding", value: "practice_grounding" },
            { label: "Provide a Quiet Space", value: "provide_a_quiet_space" },
            { label: "Reduce Stimuli", value: "reduce_stimuli" },
            { label: "Simple Mindfulness", value: "simple_mindfulness" },
            { label: "Use Calm Voice", value: "use_calm_voice" },
            { label: "Use Deep Pressure", value: "use_deep_pressure" },
            { label: "Use Visual Aids", value: "use_visual_aids" },
            { label: "Others", value: "others" },
            { label: "N/A", value: "N/A" },
        ],
    },
    {
        id: "description",
        label: "Disability Details",
        inputType: "textarea",
        placeholder: "Describe here",
        gridCols: 2,
        required: true,
    },
];

// Education and Hobbies Fields
const EducationAndHobbiesFields: FormField[] = [
    {
        id: "current_school",
        label: "Current School/Program",
        sublabel: "(name of school, grade level)",
        inputType: "text",
        placeholder: "Enter school name",
        gridCols: 1,
        required: true,
    },
    {
        id: "grade_or_education_level",
        label: "Grade or Education Level",
        inputType: "text",
        placeholder: "Enter here",
        gridCols: 1,
    },
    {
        id: "program_iep_504_plan",
        label: "Program or IEP or 504 Plan",
        sublabel: "(if applicable, include key details or goals)",
        inputType: "text",
        placeholder: "(appropriate relative to developmental level)",
        gridCols: 1,
    },
    {
        id: "cultural_religious_considerations",
        label: "Cultural/Religious Considerations",
        sublabel: "(if applicable for the program)",
        inputType: "text",
        placeholder: "Enter here",
        gridCols: 1,
    },
    {
        id: "academic_strengths",
        label: "Academic Strengths",
        sublabel: "(subjects the learner enjoys or does well in)",
        inputType: "select-creatable",
        variant: "multi",
        placeholder: "Don't see your option? Type it in to add.",
        gridCols: 1,
        disabled: false,
        options: [
            { label: "English", value: "english" },
            { label: "History", value: "history" },
            { label: "Math", value: "math" },
            { label: "Science", value: "science" },
            { label: "Computer Science", value: "computer_science" },
            { label: "Social Studies", value: "social_studies" },
            { label: "Chemistry", value: "chemistry" },
            { label: "Physics", value: "physics" },
            { label: "Biology", value: "biology" },
            { label: "Others", value: "others" },
            { label: "N/A", value: "N/A" },
        ],
        required: true,
    },
    {
        id: "extracurricular_activities",
        label: "Extracurricular Activities",
        sublabel: "(current or past participation)",
        inputType: "text",
        placeholder: "Enter here",
        gridCols: 1,
    },
    {
        id: "favorite_free_time_activities",
        label: "Favorite Free-Time Activities",
        sublabel: "(Eg., music, sports - any activity that motivates the learner)",
        inputType: "textarea",
        placeholder: "Enter here",
        gridCols: 2,
    },
];

// Skills to Learn from Volunteers Fields
const SkillsToLearnFields: FormField[] = [
    {
        id: "expected_goals",
        label: "Parent/Guardian's Goals for the learner ",
        sublabel: "(e.g., improve social skills, academic progress, explore new hobbies)",
        inputType: "select-creatable",
        variant: "multi",
        placeholder: "Don't see your option? Type it in to add.",
        gridCols: 1,
        options: [
            { label: "Boost Confidence", value: "boost_confidence" },
            { label: "Build Friendships", value: "build_friendships" },
            { label: "Encourage Activities", value: "encourage_activities" },
            { label: "Encourage Independence", value: "encourage_independence" },
            { label: "Find Family Support", value: "find_family_support" },
            { label: "Handle Sensory Issues", value: "handle_sensory_issues" },
            { label: "Improve Communication", value: "improve_communication" },
            { label: "Learn Learner's Needs", value: "learn_learners_needs" },
            { label: "Manage Emotions", value: "manage_emotions" },
            { label: "Prepare for Changes", value: "prepare_for_changes" },
            { label: "Promote Good Health", value: "promote_good_health" },
            { label: "Provide a Safe Home", value: "provide_a_safe_home" },
            { label: "Show Love and Acceptance", value: "show_love_and_acceptance" },
            { label: "Support Hobbies", value: "support_hobbies" },
            { label: "Support Learning", value: "support_learning" },
            { label: "Teach Life Skills", value: "teach_life_skills" },
            { label: "Teach Problem-Solving", value: "teach_problem_solving" },
            { label: "Teach Responsibility", value: "teach_responsibility" },
            { label: "Teach Self-Advocacy", value: "teach_self_advocacy" },
            { label: "Work with Therapists", value: "work_with_therapists" },
            { label: "Others", value: "others" },
            { label: "N/A", value: "N/A" },
        ],
        required: true,
    },
    {
        id: "academic_skills_to_learn",
        label: "Academic Skills",
        sublabel: "(academic areas for tutoring or support)",
        inputType: "async-select",
        endpoint: "skills?category=academic",
        variant: "multi",
        creatable: true,
        responseAsLabel: "skill_name",
        responseAsValue: ["skill_id", "skill_name"],
        placeholder: "Don't see your option? Type it in to add.",
        gridCols: 1,
    },
    {
        id: "academic_goals_description",
        label: "Academic Goals Description",
        inputType: "textarea",
        placeholder: "Describe here",
        gridCols: 2,
    },
    {
        id: "arts_life_skills_to_learn",
        label: "Arts & Life Skills",
        sublabel: "(non-academic areas for tutoring or support)",
        inputType: "async-select",
        endpoint: "skills?category=non_academic",
        variant: "multi",
        creatable: true,
        responseAsLabel: "skill_name",
        responseAsValue: ["skill_id", "skill_name"],
        placeholder: "Don't see your option? Type it in to add.",
        gridCols: 1,
    },
    {
        id: "arts_life_goals_description",
        label: "Arts, Life Skills & Goals Description",
        inputType: "textarea",
        placeholder: "Describe here",
        gridCols: 2,
    },
    {
        id: "preferred_volunteer_qualities",
        label: "Preferred Volunteer Qualities",
        sublabel: "(any specific traits the parent/guardian values in a tutor or mentor)",
        inputType: "text",
        placeholder: "Enter here",
        gridCols: 1,
        required: true,
    },
    {
        id: "other_comments_or_notes",
        label: "Other Comments or Notes",
        sublabel: "(anything else the program should know)",
        inputType: "textarea",
        placeholder: "Enter here",
        gridCols: 2,
    },
    {
        id: "skill_level",
        label: "Skill Level",
        sublabel: " ",
        inputType: "radio",
        options: [
            { label: "Beginner", value: "beginner" },
            { label: "Intermediate", value: "intermediate" },
            { label: "Expert", value: "expert" },
        ],
        gridCols: 1,
        className: "w-full h-fit mt-2 md:mt-4 gap-0 !mb-0",
        inputClassName: "w-full h-full",
        required: true,
    },
];

export const LearnerFormSections: FormSectionConfig[] = [
    {
        parent: "learner_personal_info",
        title: "Learner Info",
        fields: LearnerPersonalFields,
    },
    {
        parent: "parent_info",
        title: "Guardian Info",
        fields: ParentGuardianFields,
    },
    {
        title: "Profile Details",
        fields: [
            {
                parent: "learner_special_needs",
                title: "Disability-Specific Information",
                fields: DisabilityInfoFields,
            },
            {
                parent: "education",
                title: "Education and Hobbies",
                fields: EducationAndHobbiesFields,
            },
            {
                parent: "learner_goals",
                title: "Skills to Learn from Volunteers",
                fields: SkillsToLearnFields,
            },
        ],
        type: "card",
    },
    {
        title: "Profile Pic",
        parent: null,
        fields: [
            {
                id: "profile_picture",
                label: "Learner's Profile Picture",
                inputType: "upload",
                required: false,
                gridCols: 1,
                variant: "file",
                fileType: "image/*",
            },
        ],
    },
    {
        title: "Consent",
        parent: "consent_and_permissions",
        fields: [
            {
                id: "photo_or_video_consent",
                label: "Photo/Video Consent",
                sublabel: "(for use in program materials or promotional content)",
                inputType: "radio",
                options: [
                    { label: "Yes", value: true },
                    { label: "No", value: false },
                ],
                required: false,
                gridCols: 1,
            },
            // {
            //     id: "acknowledgement_of_program_policies",
            //     label: "Acknowledgment of Program Policies ",
            //     sublabel: "(Rules, Expectations, and Procedures)",
            //     options: [
            //         { label: "Yes", value: true },
            //         { label: "No", value: false },
            //     ],
            //     inputType: "radio",
            //     gridCols: 1,
            // },
        ],
    },
];

export const LearnerProfileFormSections: FormSectionConfig[] = LearnerFormSections?.filter(
    (section) => section.parent !== "consent_and_permissions"
);

export const LearnerThankyouCardConstants = {
    title: "Thank You for Enrolling in MelodyWings!",
    description:
        "We're excited to have you join our community. Our team will review your details and get back to you shortly with the next steps. We appreciate your trust in us, and we look forward to helping you on this learning journey.",
};

export const LearnerRejectedMessage = {
    title: "Thank you for your interest!",
    description:
        "At this time, we're unable to move forward with your enrollment. If you believe this was a mistake or have questions, please reach out to support@melodywings.org — we're happy to help.",
};
