import academicStrengths from "@/data/academicStrengths.json";
import techniquesThatWork from "@/data/techniquesThatWork.json";

// No Country filter: GET /volunteer/list always restricts to the learner's own country and
// ignores a client-supplied `country`, so picking another country silently did nothing.
export const VolunteerFilterModalConstants = [
    {
        name: "languages_known",
        label: "Languages Known",
        inputType: "async-select",
        variant: "multi",
        placeholder: "Select language",
        endpoint: "languages",
        responseAsLabel: "language_name",
        responseAsValue: "language_id",
    },
    {
        name: "skill_ids",
        label: "Skills and Expertise to Learn",
        inputType: "async-select",
        variant: "multi",
        endpoint: "skills",
        responseAsLabel: "skill_name",
        responseAsValue: "skill_id",
        placeholder: "Select skills to learn",
    },
    // {
    //     name: "subjects",
    //     label: "Subjects",
    //     inputType: "async-select",
    //     placeholder: "Select subjects",
    //     endpoint: "subjects",
    //     responseAsLabel: "subject_name",
    //     responseAsValue: "subject_id",
    //     variant: "multi",
    // },
    {
        name: "available_time",
        label: "Available Time",
        inputType: "timerange",
        placeholder: "Available Time",
        clearable: true,
    },
];
export const LearnerFilterModalConstants = [
    {
        name: "learner_primary_language",
        label: "Primary Language",
        inputType: "async-select",
        variant: "multi",
        placeholder: "Select language",
        endpoint: "languages",
        responseAsLabel: "language_name",
        responseAsValue: "language_name",
    },
    {
        name: "type_of_developmental_disability",
        label: "Type of Developmental Disability",
        inputType: "async-select",
        variant: "multi",
        placeholder: "Select developmental disability",
        endpoint: "development_disabilities",
        responseAsLabel: "development_disability_name",
        responseAsValue: "development_disability_name",
    },
    {
        id: "academic_strengths",
        name: "academic_strengths",
        label: "Academic Strengths",
        inputType: "select-creatable",
        variant: "multi",
        placeholder: "Select academic strengths",
        options: academicStrengths,
        showSearch: true,
    },
    {
        name: "techniques_to_calm",
        label: "Behavior Support Strategies",
        inputType: "select-creatable",
        variant: "multi",
        placeholder: "Select strategies",
        options: techniquesThatWork,
        showSearch: true,
    },
    {
        name: "skill_ids",
        label: "Skills and Expertise to Learn",
        inputType: "async-select",
        variant: "multi",
        endpoint: "skills",
        responseAsLabel: "skill_name",
        responseAsValue: "skill_id",
        placeholder: "Select skills to learn",
    },
];
